//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.org.infonavit.msrf.patron.web.ws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ControlWS", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControlWS {


    /**
     * 
     * @param correo
     * @return
     *     returns javax.xml.ws.Response<mx.org.infonavit.msrf.patron.web.ws.ResetPasswordResponse>
     */
    @WebMethod(operationName = "resetPassword")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPasswordResponse")
    public Response<ResetPasswordResponse> resetPasswordAsync(
        @WebParam(name = "correo", targetNamespace = "")
        String correo);

    /**
     * 
     * @param asyncHandler
     * @param correo
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "resetPassword")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPasswordResponse")
    public Future<?> resetPasswordAsync(
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ResetPasswordResponse> asyncHandler);

    /**
     * 
     * @param correo
     * @return
     *     returns mx.org.infonavit.msrf.patron.web.ws.ResetPassDTO
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.ResetPasswordResponse")
    public ResetPassDTO resetPassword(
        @WebParam(name = "correo", targetNamespace = "")
        String correo);

    /**
     * 
     * @param correo
     * @return
     *     returns javax.xml.ws.Response<mx.org.infonavit.msrf.patron.web.ws.GetAccessInfoResponse>
     */
    @WebMethod(operationName = "getAccessInfo")
    @RequestWrapper(localName = "getAccessInfo", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfo")
    @ResponseWrapper(localName = "getAccessInfoResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfoResponse")
    public Response<GetAccessInfoResponse> getAccessInfoAsync(
        @WebParam(name = "correo", targetNamespace = "")
        String correo);

    /**
     * 
     * @param asyncHandler
     * @param correo
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAccessInfo")
    @RequestWrapper(localName = "getAccessInfo", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfo")
    @ResponseWrapper(localName = "getAccessInfoResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfoResponse")
    public Future<?> getAccessInfoAsync(
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetAccessInfoResponse> asyncHandler);

    /**
     * 
     * @param correo
     * @return
     *     returns mx.org.infonavit.msrf.patron.web.ws.AccesoDTO
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getAccessInfo", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfo")
    @ResponseWrapper(localName = "getAccessInfoResponse", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", className = "mx.org.infonavit.msrf.patron.web.ws.GetAccessInfoResponse")
    public AccesoDTO getAccessInfo(
        @WebParam(name = "correo", targetNamespace = "")
        String correo);

}
