//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.org.infonavit.msrf.patron.web.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ControlWSService", targetNamespace = "http://ws.web.patron.msrf.infonavit.org.mx/", wsdlLocation = "WEB-INF/wsdl/control.wsdl")
public class ControlWSService
    extends Service
{

    private final static URL CONTROLWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLWSSERVICE_EXCEPTION;
    private final static QName CONTROLWSSERVICE_QNAME = new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "ControlWSService");

    static {
            CONTROLWSSERVICE_WSDL_LOCATION = mx.org.infonavit.msrf.patron.web.ws.ControlWSService.class.getResource("/WEB-INF/wsdl/control.wsdl");
        WebServiceException e = null;
        if (CONTROLWSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/control.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONTROLWSSERVICE_EXCEPTION = e;
    }

    public ControlWSService() {
        super(__getWsdlLocation(), CONTROLWSSERVICE_QNAME);
    }

    public ControlWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLWSSERVICE_QNAME, features);
    }

    public ControlWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLWSSERVICE_QNAME);
    }

    public ControlWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLWSSERVICE_QNAME, features);
    }

    public ControlWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControlWS
     */
    @WebEndpoint(name = "ControlWSPort")
    public ControlWS getControlWSPort() {
        return super.getPort(new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "ControlWSPort"), ControlWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlWS
     */
    @WebEndpoint(name = "ControlWSPort")
    public ControlWS getControlWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "ControlWSPort"), ControlWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLWSSERVICE_EXCEPTION!= null) {
            throw CONTROLWSSERVICE_EXCEPTION;
        }
        return CONTROLWSSERVICE_WSDL_LOCATION;
    }

}
