//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package mx.org.infonavit.msrf.patron.web.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.org.infonavit.msrf.patron.web.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAccessInfoResponse_QNAME = new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "getAccessInfoResponse");
    private final static QName _ResetPasswordResponse_QNAME = new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "resetPasswordResponse");
    private final static QName _GetAccessInfo_QNAME = new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "getAccessInfo");
    private final static QName _ResetPassword_QNAME = new QName("http://ws.web.patron.msrf.infonavit.org.mx/", "resetPassword");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.org.infonavit.msrf.patron.web.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResetPassword }
     * 
     */
    public ResetPassword createResetPassword() {
        return new ResetPassword();
    }

    /**
     * Create an instance of {@link GetAccessInfoResponse }
     * 
     */
    public GetAccessInfoResponse createGetAccessInfoResponse() {
        return new GetAccessInfoResponse();
    }

    /**
     * Create an instance of {@link ResetPasswordResponse }
     * 
     */
    public ResetPasswordResponse createResetPasswordResponse() {
        return new ResetPasswordResponse();
    }

    /**
     * Create an instance of {@link GetAccessInfo }
     * 
     */
    public GetAccessInfo createGetAccessInfo() {
        return new GetAccessInfo();
    }

    /**
     * Create an instance of {@link ResetPassDTO }
     * 
     */
    public ResetPassDTO createResetPassDTO() {
        return new ResetPassDTO();
    }

    /**
     * Create an instance of {@link WasResponseDTO }
     * 
     */
    public WasResponseDTO createWasResponseDTO() {
        return new WasResponseDTO();
    }

    /**
     * Create an instance of {@link AccesoDTO }
     * 
     */
    public AccesoDTO createAccesoDTO() {
        return new AccesoDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccessInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.web.patron.msrf.infonavit.org.mx/", name = "getAccessInfoResponse")
    public JAXBElement<GetAccessInfoResponse> createGetAccessInfoResponse(GetAccessInfoResponse value) {
        return new JAXBElement<GetAccessInfoResponse>(_GetAccessInfoResponse_QNAME, GetAccessInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.web.patron.msrf.infonavit.org.mx/", name = "resetPasswordResponse")
    public JAXBElement<ResetPasswordResponse> createResetPasswordResponse(ResetPasswordResponse value) {
        return new JAXBElement<ResetPasswordResponse>(_ResetPasswordResponse_QNAME, ResetPasswordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccessInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.web.patron.msrf.infonavit.org.mx/", name = "getAccessInfo")
    public JAXBElement<GetAccessInfo> createGetAccessInfo(GetAccessInfo value) {
        return new JAXBElement<GetAccessInfo>(_GetAccessInfo_QNAME, GetAccessInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.web.patron.msrf.infonavit.org.mx/", name = "resetPassword")
    public JAXBElement<ResetPassword> createResetPassword(ResetPassword value) {
        return new JAXBElement<ResetPassword>(_ResetPassword_QNAME, ResetPassword.class, null, value);
    }

}
